# Generated by Django 5.1.3 on 2024-12-19 03:28

import django.db.models.deletion
import nfctags.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NFCTagBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='A descriptive name for this batch of NFC Tags.', max_length=255, verbose_name='Batch Name')),
                ('description', models.TextField(blank=True, help_text='Optional description for this batch.', null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(blank=True, help_text='The user of this batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_tag_batches', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'NFC Tag Batch',
                'verbose_name_plural': 'NFC Tag Batches',
            },
        ),
        migrations.CreateModel(
            name='NFCTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('uid', models.CharField(db_index=True, editable=False, max_length=32, unique=True, validators=[nfctags.validators.validate_ascii_mirror_uid])),
                ('content', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='nfc_tags', to='nfctags.nfctagbatch')),
            ],
            options={
                'verbose_name': 'NFC Tag',
                'verbose_name_plural': 'NFC Tags',
                'ordering': ['uid'],
            },
        ),
    ]
